### ISSUE TITLE
MultiCardMenu 出现位置错乱

### ISSUE THREAD

**Issue by zzy0990** [wujingchao/MultiCardMenu#2]
在simple:background_layout里面放一个viewpager，且viewpager页数超过3页，先点击Jelly Bean弹出后，在关闭，然后滑动viewpager，底部的MultiCardMenu就会出现位置错乱。一直找不到触发错乱的原因

**Comment by wujingchao** [comment]
目测原因就是viewpager超过3页之后滑动就会调用requestLayout，MultiCardMenu就会调用onLayout方法导致的，目前没有比较好的办法，待周末头脑清醒再提交代码，如果你有比较好的办法可以提交PR:)

**Comment by wujingchao** [comment]
貌似新版本的ViewPager没有这个问题，但是有另外一个问题会出现空白，一次性加载就不会有这个问题，mViewPager.setOffscreenPageLimit(imgRes.length);
