### ISSUE TITLE
Put cards in scrollview

### ISSUE THREAD

**Issue by amitbhoraniya** [wujingchao/MultiCardMenu#3]
I want to put all cards in scrollview, because in my case if more than 7-8 menu then I required scrollablity for card, any help would be appreciated.

**Comment by wujingchao** [comment]
You can reference SystemUI's [RecentsActivity](https://android.googlesource.com/platform/frameworks/base/+/7ed267f/packages/SystemUI/src/com/android/systemui/recent/RecentsActivity.java).RecentsPanelView like this:

![RecentsActivity](https://developer.android.com/images/components/recents.png)

It's a little hard to read.Good luck,friend!!!

**Comment by amitbhoraniya** [comment]
Thanks Buddy. :+1:
