### ISSUE TITLE
please provide me solution for scroll ability when we are adding more items

### ISSUE THREAD

**Issue by vigneswarandavarapu** [wujingchao/MultiCardMenu#4]

**Comment by wujingchao** [comment]
You can reference SystemUI's [RecentsActivity](https://android.googlesource.com/platform/frameworks/base/+/7ed267f/packages/SystemUI/src/com/android/systemui/recent/RecentsActivity.java).RecentsPanelView like this:

![RecentsActivity](https://developer.android.com/images/components/recents.png)

It's a little hard to read.Good luck,friend!!!
